version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/data:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - NEXT_PUBLIC_FASTAPI_BASE_URL=http://python:8000

  python:
    build:
      context: ./python
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - qdrant
    environment:
      - QDRANT_URL_BASE=http://qdrant:6333

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
  ollama:
