version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/data:/app/data

  python:
    build:
      context: ./python
    ports:
      - "8000:8000"
